#!/usr/bin/python3
#
#	pyglmahjong - Python OpenGL Mahjong and Shisen implementation
#	Copyright (C) 2015-2018 Johannes Bauer
#
#	This file is part of pyglmahjong.
#
#	pyglmahjong is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	pyglmahjong is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with pyglmahjong; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
from XMLParser import XMLNode

(width, height) = (int(sys.argv[1]), int(sys.argv[2]))

xml = XMLNode("layout")
xml["grid"] = "1"
xml["name"] = "Shisen %dx%x" % (width, height)
for x in range(width):
	for z in range(height):
		xml.addchild("piece", x = str(x), y = "0", z = str(z))

xmlfilename = "layout_shisen_%d_%d.xml" % (width, height)
xml.write(open(xmlfilename, "w"), pretty = True)

